//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FplBot.Tests.Helpers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FplBot.Tests.Helpers.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;events&quot;:[{&quot;id&quot;:1,&quot;name&quot;:&quot;Gameweek 1&quot;,&quot;deadline_time&quot;:&quot;2020-09-12T10:00:00Z&quot;,&quot;average_entry_score&quot;:50,&quot;finished&quot;:true,&quot;data_checked&quot;:true,&quot;highest_scoring_entry&quot;:4761681,&quot;deadline_time_epoch&quot;:1599904800,&quot;deadline_time_game_offset&quot;:0,&quot;highest_score&quot;:142,&quot;is_previous&quot;:false,&quot;is_current&quot;:false,&quot;is_next&quot;:false,&quot;chip_plays&quot;:[{&quot;chip_name&quot;:&quot;bboost&quot;,&quot;num_played&quot;:112843},{&quot;chip_name&quot;:&quot;3xc&quot;,&quot;num_played&quot;:225426}],&quot;most_selected&quot;:259,&quot;most_transferred_in&quot;:12,&quot;top_element&quot;:254,&quot;top_element_info&quot;:{&quot;id&quot;:254,&quot;points&quot;:20}, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Boostrap_Static_Json {
            get {
                return ResourceManager.GetString("Boostrap-Static-Json", resourceCulture);
            }
        }
    }
}
