docker run \
--rm \
-e DOTNET_ENVIRONMENT=Development \
-e NSB_LICENSE="$NSB_LICENSE" \
-e ASB_CONNECTIONSTRING=$ASB_CONNECTIONSTRING \
-e REDIS_URL=$REDIS_URL \
-e fpl__login=$fpl__login \
-e fpl__password=$fpl__password \
-e CLIENT_ID=$CLIENT_ID \
-e CLIENT_SECRET=$CLIENT_SECRET \
-e CLIENT_SIGNING_SECRET=$CLIENT_SIGNING_SECRET \
-e DISCORD_CLIENT_ID=$DISCORD_CLIENT_ID \
-e DISCORD_CLIENT_SECRET=$DISCORD_CLIENT_SECRET \
-e DISCORD_TOKEN=$DISCORD_TOKEN \
-p 1337:1337 \
fplbot-webapi:heroku
