name: CI

on:
  push:
    branches:
      - "**"
      - "main"
  pull_request:

jobs:
  ci-on-ubuntu:
    if: >
      github.event_name != 'pull_request' ||
      github.event.pull_request.head.repo.full_name != github.repository
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: "10.0.x"
      - name: Test
        run: dotnet run --project src/Build -- test
