name: CI

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  ci-on-ubuntu:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: "10.0.x"
      - name: CI
        run: dotnet run --project src/Build -- ci --parallel
