name: deploy-to-test

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  deploy-ubuntu-test:
    name: deploy-to-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      packages: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "10.0.x"
      - name: start deployment
        uses: bobheadxi/deployments@v0.4.3
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: test
          ref: ${{ github.head_ref }}
      - run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: "5.x"
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh
      - name: Build docker images
        run: dotnet run --project src/Build -- docker-build
        env:
          VERSION: ${{ steps.gitversion.outputs.fullSemVer }}
          INFOVERSION: ${{ steps.gitversion.outputs.informationalVersion }}
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/login-action@v1
        with:
          registry: registry.heroku.com
          username: _
          password: ${{ secrets.HEROKU_TOKEN }}
      - name: Push docker images to Heroku
        run: dotnet run --project src/Build -- docker-push-test
      - name: Deploy to test
        run: dotnet run --project src/Build -- deploy-test
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}
      - name: update deployment status
        uses: bobheadxi/deployments@v0.4.3
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
